sudo: required
dist: trusty
language: node_js
node_js:
  - 7.4
env:
  matrix:
    - MONGODB_VERSION=3.4.x MONGODB_TOPOLOGY=standalone
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libkrb5-dev
      - libsecret-1-0
before_install:
  - echo "//registry.npmjs.org/:_authToken=c3c41e28-29d4-429b-9128-1e3502f16f0e" >> .npmrc
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm run check
script: npm run test
cache:
  directories:
    - $HOME/.electron
    - node_modules
